#define TK_QUIT                            1
#define TK_SELECT                          2
#define TK_DISTINCT                        3
#define TK_ID                              4
#define TK_STRING                          5
#define TK_STAR                            6
#define TK_COMMA                           7
#define TK_FROM                            8
#define TK_GT                              9
#define TK_LT                             10
#define TK_EQ                             11
#define TK_INTEGER                        12
#define TK_NOT                            13
#define TK_AND                            14
#define TK_OR                             15
#define TK_WHERE                          16
#define TK_ASC                            17
#define TK_DESC                           18
#define TK_ORDER                          19
#define TK_BY                             20
#define TK_LIMIT                          21
