#define TK_SELECT                          1
#define TK_DISTINCT                        2
#define TK_ID                              3
#define TK_STRING                          4
#define TK_STAR                            5
#define TK_COMMA                           6
#define TK_FROM                            7
#define TK_GT                              8
#define TK_LT                              9
#define TK_EQ                             10
#define TK_INTEGER                        11
#define TK_NOT                            12
#define TK_AND                            13
#define TK_OR                             14
#define TK_WHERE                          15
#define TK_ORDER                          16
#define TK_BY                             17
#define TK_ASC                            18
#define TK_DESC                           19
#define TK_LIMIT                          20
