#define TK_QUIT                            1
#define TK_SELECT                          2
#define TK_DISTINCT                        3
#define TK_ID                              4
#define TK_STRING                          5
#define TK_FLOAT                           6
#define TK_INTEGER                         7
#define TK_STAR                            8
#define TK_COMMA                           9
#define TK_FROM                           10
#define TK_PLUS                           11
#define TK_MINUS                          12
#define TK_DIV                            13
#define TK_MOD                            14
#define TK_NOT                            15
#define TK_OR                             16
#define TK_AND                            17
#define TK_LIKE                           18
#define TK_GT                             19
#define TK_LT                             20
#define TK_EQ                             21
#define TK_GE                             22
#define TK_LE                             23
#define TK_NE                             24
#define TK_LP                             25
#define TK_RP                             26
#define TK_WHERE                          27
#define TK_ASC                            28
#define TK_DESC                           29
#define TK_ORDER                          30
#define TK_BY                             31
#define TK_LIMIT                          32
